spring:
  config:
    location: classpath:application.yml,classpath:formula-config.yml
  datasource:
    url: jdbc:mysql://localhost:3306/Email?useSSL=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: Payalgbu493@gmail.com
    password: ubfx pzry ezvs xvlv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

